In [4]:
from   baggingrnet.bagmodel.config import  baggingpath

In [6]:
baggingpath="/dsdfsdffdfsfd"

In [7]:
baggingpath

'/dsdfsdffdfsfd'

In [8]:
from   baggingrnet.bagmodel.config import  baggingpath
baggingpath

'\tmp'

In [16]:
from numpy.random import choice
import numpy as np 
aa=choice( np.array([1,2,3,4,5,6]),size=6)

In [17]:
aa

array([6, 5, 3, 1, 2, 1])

In [18]:
np.unique(aa)

array([1, 2, 3, 5, 6])

In [19]:
nfea=10 
np.unique(np.random.choice(range(nfea),nfea))

array([0, 1, 2, 3, 5, 9])

In [24]:
ad='wer'
type(ad)==str

True

In [22]:
type(ad)

str

In [26]:
a=['23','ert']
type(a)==str

False